import "fs";
import { writeFileSync } from "fs";
import { activityColors } from "./src/app/models/activityColors";

let colorCss = `/* This file is autogenerated from ./src/app/models/activityColors
 * Use npm run generate:colors to update it.
 */
`;
for (const activityColor of activityColors) {
    colorCss += `.${activityColor.styleClass} {
  background-color: rgb(${activityColor.color.r}, ${activityColor.color.g}, ${activityColor.color.b});
}

`;
}

writeFileSync("./src/colors.css", colorCss, "utf-8");
